### ISSUE TITLE
Webui refiner

### ISSUE THREAD

**Issue by dasadawd** [camenduru/sdxl-colab#13]
connection errored out when I change the model to refiner in webui

**Comment by funkykanky** [comment]
yes! same here... can't pick refiner at all.

**Comment by A2R14N** [comment]
so when ram is close to 100% 
![image](https://github.com/camenduru/sdxl-colab/assets/81319192/c502e984-f942-41bf-a7bf-d9108da6d15c)
it fails..

**Comment by camenduru** [comment]
please test new version
