### ISSUE TITLE
Can’t switch checkpoints

### ISSUE THREAD

**Issue by Hoozzych** [camenduru/sdxl-colab#9]
**### I can’t switch to the DreamShaper XL1.0 Alpha2 model, when I replace the code line it automatically switches to the horrifying v1-5-pruned-emaonly.safetensors model**

![1](https://github.com/camenduru/sdxl-colab/assets/112584638/1ab383a4-3866-45be-bab2-9d36c14e9b6f)
![2](https://github.com/camenduru/sdxl-colab/assets/112584638/551031bb-c12d-4217-ad59-1ca5d49334e3)
![3](https://github.com/camenduru/sdxl-colab/assets/112584638/2bcd1905-5b38-4316-a634-985c3cc4ade8)

**Comment by camenduru** [comment]
please try this "https://civitai.com/api/download/models/126688"
